name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Uncomment and adjust Node.js setup if needed
      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'  # Adjust the version as needed

      - name: Install Dependencies
        run: |
          npm install  # Use 'npm install' for clarity

      - name: Build Project
        run: |
          npm run build  # Assuming you have a build script
          npm install -g pm2 

jobs1:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Stop Applications
        run: |
          pm2 kill
          
      - name: Start Applications
        run: |    
          cd ~/actions-runner/_work/sample-react-todo-app/sample-react-todo-app/
          
          pm2 start "npm run start" --name to-do-app --cwd ~/actions-runner/_work/sample-react-todo-app/sample-react-todo-app/

      - name: Notify Deployment Status
        run: |
          echo "Deployment completed successfully!"

          pm2 list  # Display PM2 process list for verification
